### ISSUE TITLE
Add option to include original exception message?

### ISSUE THREAD

**Issue by mastrzyz** [vcfvct/typescript-retry-decorator#12]
Would be fantastic to include the original exception message that caused the final retry

Currently we see

`Error: Failed for 'foo' for 2 times.`

Would like to see 

`Error: Failed for 'fo' for 2 times . Orginal Error : 'Null PTR Exception'`

**Comment by vcfvct** [comment]
@mastrzyz 
Sure, sounds good. Theoretically it should [log error after last retry](https://github.com/vcfvct/typescript-retry-decorator/blob/master/src/retry.decorator.ts#L43). 
finally get some time on weekend. let me try to verify it and find a proper way to add this message to the final exception it throws.

**Comment by vcfvct** [comment]
implemented in #13
