### ISSUE TITLE
Add option to throw the original exception

### ISSUE THREAD

**Issue by bm77525-kr** [vcfvct/typescript-retry-decorator#17]
I know the original error _message_ is included when retries are exhausted, but it would be great to have the option to bubble up the original error instance itself stack trace and all. This would, of course, not be expected to be enabled by default as it would be a breaking change to existing functionality, but I imagine it could be enabled via the options.

**Comment by vcfvct** [comment]
on vacation.
make sense. would take a look later 😄

**Comment by wells1013** [comment]
+1

**Comment by vcfvct** [comment]
closing this. 
Addressed by #23 .
