### ISSUE TITLE
Add an option to retry specific error classes

### ISSUE THREAD

**Issue by bogdan** [vcfvct/typescript-retry-decorator#9]
A common use case is to retry errors of certain types like `FetchError` or similar. `doRetry` does the job, but it is inconvenient for such a common use case.

Is it possible to add an option like `errors: ErrorConstructor[] | ErrorConstructor` to specify which error classes need to be retried?

**Comment by vcfvct** [comment]
@bogdan , would you clarify a bit more on the option you mentioned and your use case? 
in terms of `FetchError`, do you mean the one in `node-fetch` library?

**Comment by bogdan** [comment]
It is easy: you want to retry a network connection error when interacting with remote host.
The simple way of doing that is try target `FetchError` specifically.

Here is how it may look like:

```
@Retryable({ 
    maxAttempts: 3,
    errors: FetchError,
})
requestOauth() {
  return fetch(this.url);
}
```

**Comment by vcfvct** [comment]
busy days...
 added a `value` option similar to what's in Spring that you can specify an array of exception types for retry in #10
